SELECT * 
	  FROM CUSTOMER
	  JOIN ORDEN 
		ON CUSTOMER.ID_CUSTOMER = ORDEN.ID_CUSTOMER
	 WHERE CUSTOMER.FNACIMIENTO = GETDATE()
	   AND CUSTOMER.ID_CUSTOMER IN (
									  SELECT TABLE_SUM.ID_CUSTOMER
										FROM (
										   SELECT SUM(ORDEN.ID_CUSTOMER) AS SUM_USUARIO, ORDEN.ID_CUSTOMER AS ID_CUSTOMER 
										   FROM CUSTOMER
										   JOIN ORDEN
											 ON CUSTOMER.ID_CUSTOMER = ORDEN.ID_CUSTOMER
										  WHERE CAST(YEAR(FVENTA) AS VARCHAR)+CAST(MONTH(FVENTA) AS VARCHAR) = '20201'
									   GROUP BY ORDEN.ID_CUSTOMER
									   ORDER BY SUM_USUARIO ASC
										) TABLE_SUM
										WHERE TABLE_SUM.SUM_USUARIO > 1500
									)

	SELECT MONTH(ORDEN.FVENTA) AS MES, YEAR(ORDEN.FVENTA) AS AÑO, CUSTOMER.NOMBRE AS NOMBRE, CUSTOMER.APELLIDO AS APELLIDO, TOP_USUARIOS.TOTAL_VENTAS AS TOTAL_VENTAS, TOP_USUARIOS.TOTAL_PRECIO AS TOTAL_PRECIO
	FROM CUSTOMER
	JOIN ORDEN
	  ON CUSTOMER.ID_CUSTOMER = ORDEN.ID_CUSTOMER
	JOIN (
			SELECT TOP 5 COUNT(ITEM.ID_ITEM) AS TOTAL_VENTAS, SUM(ITEM.PRECIO) AS TOTAL_PRECIO, CUSTOMER.ID_CUSTOMER AS ID_CUSTOMER 
			  FROM CUSTOMER
			  JOIN ORDEN
				ON ORDEN.ID_CUSTOMER = CUSTOMER.ID_CUSTOMER
			  JOIN ITEM 
				ON ITEM.ID_ITEM= ORDEN.ID_ITEM
			  JOIN CATEGORY
				ON CATEGORY.ID_CATEGORIA = ITEM.ID_CATEGORIA
			 WHERE CATEGORY.NOMBRE LIKE 'CELULARES'
		  GROUP BY	CAST(YEAR(FVENTA) AS VARCHAR)+CAST(MONTH(FVENTA) AS VARCHAR),
					CUSTOMER.ID_CUSTOMER
		  ORDER BY COUNT(CUSTOMER.ID_CUSTOMER) ASC 
	) TOP_USUARIOS
  ON CUSTOMER.ID_CUSTOMER = TOP_USUARIOS.ID_CUSTOMER


 CREATE PROCEDURE dbo.ACTUALIZAR_TABLA_ITEM_ESTADOS
@DIA DATETIME
AS
	INSERT INTO ESTADO_ITEM
		SELECT ITEM.ID_ITEM, ITEM.PRODUCTO, ORDEN.PRECIO AS PRECIO, 'CERRADO' AS ESTADO 
		  FROM ITEM
		  JOIN ORDEN 
			ON ORDEN.ID_ITEM = ORDEN.ID_ITEM
		 WHERE ORDEN.FVENTA = @DIA
	UNION
		SELECT ITEM.ID_ITEM, ITEM.PRODUCTO, ORDEN.PRECIO AS PRECIO, 'ABIERTO' AS ESTADO 
		  FROM ITEM
		  LEFT OUTER JOIN ORDEN 
			ON ITEM.ID_ITEM = ORDEN.ID_ITEM
		  LEFT OUTER JOIN ESTADO_ITEM 
			ON ITEM.ID_ITEM = ESTADO_ITEM.ID_ITEM
		 WHERE ESTADO_ITEM.ID_ITEM IS NULL
		   AND ORDEN.ID_ITEM IS NULL